services:
  - type: web
    name: image-gen-server
    env: node
    buildCommand: npm install --force
    startCommand: node --experimental-specifier-resolution=node Server.js
    envVars:
      - key: PORT
        value: "5000"
      - key: MONGODB_URI
        fromSecret: MONGODB_URI
      - key: JWT_SECRET
        fromSecret: JWT_SECRET
      - key: RAZORPAY_KEY_ID
        fromSecret: RAZORPAY_KEY_ID
      - key: RAZORPAY_KEY_SECRET
        fromSecret: RAZORPAY_KEY_SECRET
      - key: CURRENCY
        value: "INR"
      - key: NODE_ENV
        value: "production"